#!/usr/bin/env python

# Sagemaker expects to have a model definition in /opt/ml/model
# We don't want to train hence We copy the trained model to that location,

import os
import sys
import traceback
import shutil

# These are the paths to where SageMaker mounts interesting things in your container.
prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')  # make it a dict with kwargs


def train():
    try:
        os.makedirs('/opt/ml/model/', exist_ok=True)
        shutil.copy2('/opt/program/saved_model/isnet.pth', '/opt/ml/model/isnet.pth')
        print('Training complete!!')
    except Exception as e:
        trc = traceback.format_exc()
        with open(os.path.join(output_path, 'failure'), 'w') as s:
            s.write('Exception during training: ' + str(e) + '\n' + trc)
        print('Exception during training: ' + str(e) + '\n' + trc)
        sys.exit(255)


if __name__ == '__main__':
    train()
    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)